-- DROP TABLE persons;

CREATE TABLE persons (
    -- id INT AUTO_INCREMENT PRIMARY KEY,
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(125) NOT NULL,
    alias VARCHAR(512) NOT NULL,
    tags VARCHAR(2048) DEFAULT NULL
);