-- DROP TABLE IF EXISTS person;

CREATE TABLE IF NOT EXISTS person (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    account_id VARCHAR(250) NOT NULL,
    name VARCHAR(250) NOT NULL,
    token VARCHAR(250) DEFAULT NULL
);