server:
  port: 8800

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  server:
    address: 127.0.0.1
    port: 8810

logging:
  level:
    com:
      peter:
        solo: debug
        markdown:
          mapper: info

solo:
  debug:
    monitor:
      # 是否开启文件监控
      enable: true
  input:
    # 上传的URI
    url: http://blog.peteryan.top:8080/plugin/markdown/input
  blog:
    # 监控的目录
    root: /Users/mac/Codes/pgits/soloblog
    temp: /Users/mac/.var/tmp/blog
    refresh:
      # 刷新时间30分钟
      interval: 1800000


spring:
  datasource:
    # 此为开关，是否屏蔽建表语句。always, embedded, never
    # 根据schema.sql建表(DDL scripts)，根据data.sql插入数据(DML scripts)。
    initialization-mode: never
    schema: classpath:db/schema-derby.sql
    data: classpath:db/data-derby.sql
    url: jdbc:derby:/Users/mac/.var/derby/testdb;create=true;
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    # driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    username: sa
    password: password
