-- DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    account_id VARCHAR(250) NOT NULL,
    name VARCHAR(250) NOT NULL,
    token VARCHAR(250) DEFAULT NULL
);